name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # O workflow será acionado sempre que houver um push (merge) na branch main

jobs:
  build:
    runs-on: ubuntu-latest # Define o sistema operacional onde o workflow será executado
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2 
      - name: Login to github container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker Image
        run: docker build -t ghcr.io/jadson-pimentel/bigChat:1.0 #"$(cat deploy-settings.json | jq -r .version)" .
      - name: Push Docker Image
        run: docker push ghcr.io/jadson-pimentel/bigChat:1.0 #"$(cat deploy-settings.json | jq -r .version)"